### ISSUE TITLE
Crestron Home connection

### ISSUE THREAD

**Issue by ViperNY** [evgolsh/homebridge-crestron-home#13]
**Describe The Bug:**
error logine in and error retreiving devices

**To Reproduce:**
auto start of the plugin

**Expected behavior:**
looking to populate and control my Crestron 
Home system via Apple Homekit

**Logs:**

```[20/05/2024, 18:43:16] [Crestron Home Platform] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)
[20/05/2024, 18:43:46] [Crestron Home Platform] Updating Devices state
[20/05/2024, 18:43:46] [Crestron Home Platform] Login error:  connect ECONNREFUSED 192.168.1.200:443
[20/05/2024, 18:43:46] [Crestron Home Platform] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)

Show the Homebridge logs here, remove any sensitive information.
```[20/05/2024, 18:43:16] [Crestron Home Platform] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)
[20/05/2024, 18:43:46] [Crestron Home Platform] Updating Devices state
[20/05/2024, 18:43:46] [Crestron Home Platform] Login error:  connect ECONNREFUSED 192.168.1.200:443
[20/05/2024, 18:43:46] [Crestron Home Platform] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)


**Plugin Config:**

```json

{
    "bridge": {
        "name": "Homebridge 0B03",
        "username": "0E:26:7C:23:0B:03",
        "port": 51489,
        "pin": "635-03-320",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Crestron Home Platform",
            "crestronHost": "192.168.1.200",
            "token": "LYJ9TjQWWM5t",
            "enabledTypes": [
                "Switch",
                "Dimmer"
            ],
            "updateInterval": 30,
            "platform": "CrestronHomePlatform"
        }
    ]
}

**Screenshots:**


**Environment:**

* **Plugin Version**:
* **Homebridge Version**: <!-- homebridge -V -->v1.8.2
* **Node.js Version**: <!-- node -v -->20.13.1
* **NPM Version**: <!-- npm -v -->dont know where to find
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service --> Debain 64bit

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by evgolsh** [comment]
connect ECONNREFUSED 192.168.1.200:443 means connection refused. Please check your network, it is not related to the plugin.
