### ISSUE TITLE
After updating Crestron Home to 4.004.0232, Homebridge stopped working

### ISSUE THREAD

**Issue by garveshb** [evgolsh/homebridge-crestron-home#16]
[07/12/2024, 12:52:43] [Crestron Home Platform Lights] Updating Devices state
[07/12/2024, 12:52:43] [Crestron Home Platform Shade Scene] Updating Devices state
[07/12/2024, 12:52:58] [Crestron Home Platform Shade Scene] Login error:  Request failed with status code 500
[07/12/2024, 12:52:58] [Crestron Home Platform Lights] Login error:  Request failed with status code 500
[07/12/2024, 12:52:58] [Crestron Home Platform Shade Scene] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)
[07/12/2024, 12:52:58] [Crestron Home Platform Lights] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/var/lib/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)

**Comment by evgolsh** [comment]
Did you try to restart the controller?

**Comment by garveshb** [comment]
Restarting Crestron Processor solved the issue, However, I was restarting HomeBridge but didn't think to restart the processor.

Thanks
